const cloudbase = require("@cloudbase/node-sdk");

// Initialize CloudBase SDK
const app = cloudbase.init({
  env: "your-env-id" // Replace with your CloudBase environment ID
});

// Main function to generate and store plans
exports.main = async (event, context) => {
  try {
    // 1. Initialize data model
    const models = app.models;
    
    // 2. Generate plan data based on logic
    const planData = {
      title: "Weekly Plan",
      description: "This is a sample plan generated by the cloud function.",
      startDate: new Date().toISOString(),
      endDate: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000).toISOString(),
      status: "active"
    };

    // 3. Validate data (optional, can be handled by data model)
    if (!planData.title || !planData.description) {
      throw new Error("Plan data is incomplete.");
    }

    // 4. Store or return data
    const { data } = await models.plan.create({
      data: planData
    });

    return {
      success: true,
      data: data
    };
  } catch (error) {
    console.error("Error generating plan:", error);
    return {
      success: false,
      error: error.message
    };
  }
};